server:
  port: 8080 #端口号要根据前端request.js对应


logging:
  level:
    root: info #设置级别

spring:
  data:
    redis:
      host: 47.94.86.115
      port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql:///exam_system_new?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  servlet:
    multipart:
      max-request-size: 150MB
      max-file-size: 100MB

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full #开启嵌套自动映射
    map-underscore-to-camel-case: true

# minio的配置
minio:
  endpoint: http://47.94.86.115:9000
  username: minioadmin
  password: minioadmin
  bucket-name: exam0625

kimi:
  api:
    model: moonshot-v1-32k
    uri: https://api.moonshot.cn/v1/chat/completions
    api-key: sk-0FjcIWCa6i6jvSu3RMHVk8ujkL8FcsoRvtkg119jij7FQB2T
    max-tokens: 4096
    temperature: 0.3
